/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UseSyncExternalStoreIndexImport } from './routes/use-sync-external-store/index'
import { Route as SubscribePatternIndexImport } from './routes/subscribe-pattern/index'
import { Route as SubscribePatternRxJsIndexImport } from './routes/subscribe-pattern/rx-js/index'
import { Route as SubscribePatternObserverPatternIndexImport } from './routes/subscribe-pattern/observer-pattern/index'
import { Route as SubscribePatternEventEmitterIndexImport } from './routes/subscribe-pattern/event-emitter/index'
import { Route as ConceptsDebounceIndexImport } from './routes/concepts/debounce/index'
import { Route as ComponentsSignupFormIndexImport } from './routes/components/signup-form/index'
import { Route as ComponentsNestedCheckboxIndexImport } from './routes/components/nested-checkbox/index'
import { Route as ComponentsContactFormIndexImport } from './routes/components/contact-form/index'

// Create/Update Routes

const UseSyncExternalStoreIndexRoute = UseSyncExternalStoreIndexImport.update({
  id: '/use-sync-external-store/',
  path: '/use-sync-external-store/',
  getParentRoute: () => rootRoute,
} as any)

const SubscribePatternIndexRoute = SubscribePatternIndexImport.update({
  id: '/subscribe-pattern/',
  path: '/subscribe-pattern/',
  getParentRoute: () => rootRoute,
} as any)

const SubscribePatternRxJsIndexRoute = SubscribePatternRxJsIndexImport.update({
  id: '/subscribe-pattern/rx-js/',
  path: '/subscribe-pattern/rx-js/',
  getParentRoute: () => rootRoute,
} as any)

const SubscribePatternObserverPatternIndexRoute =
  SubscribePatternObserverPatternIndexImport.update({
    id: '/subscribe-pattern/observer-pattern/',
    path: '/subscribe-pattern/observer-pattern/',
    getParentRoute: () => rootRoute,
  } as any)

const SubscribePatternEventEmitterIndexRoute =
  SubscribePatternEventEmitterIndexImport.update({
    id: '/subscribe-pattern/event-emitter/',
    path: '/subscribe-pattern/event-emitter/',
    getParentRoute: () => rootRoute,
  } as any)

const ConceptsDebounceIndexRoute = ConceptsDebounceIndexImport.update({
  id: '/concepts/debounce/',
  path: '/concepts/debounce/',
  getParentRoute: () => rootRoute,
} as any)

const ComponentsSignupFormIndexRoute = ComponentsSignupFormIndexImport.update({
  id: '/components/signup-form/',
  path: '/components/signup-form/',
  getParentRoute: () => rootRoute,
} as any)

const ComponentsNestedCheckboxIndexRoute =
  ComponentsNestedCheckboxIndexImport.update({
    id: '/components/nested-checkbox/',
    path: '/components/nested-checkbox/',
    getParentRoute: () => rootRoute,
  } as any)

const ComponentsContactFormIndexRoute = ComponentsContactFormIndexImport.update(
  {
    id: '/components/contact-form/',
    path: '/components/contact-form/',
    getParentRoute: () => rootRoute,
  } as any,
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subscribe-pattern/': {
      id: '/subscribe-pattern/'
      path: '/subscribe-pattern'
      fullPath: '/subscribe-pattern'
      preLoaderRoute: typeof SubscribePatternIndexImport
      parentRoute: typeof rootRoute
    }
    '/use-sync-external-store/': {
      id: '/use-sync-external-store/'
      path: '/use-sync-external-store'
      fullPath: '/use-sync-external-store'
      preLoaderRoute: typeof UseSyncExternalStoreIndexImport
      parentRoute: typeof rootRoute
    }
    '/components/contact-form/': {
      id: '/components/contact-form/'
      path: '/components/contact-form'
      fullPath: '/components/contact-form'
      preLoaderRoute: typeof ComponentsContactFormIndexImport
      parentRoute: typeof rootRoute
    }
    '/components/nested-checkbox/': {
      id: '/components/nested-checkbox/'
      path: '/components/nested-checkbox'
      fullPath: '/components/nested-checkbox'
      preLoaderRoute: typeof ComponentsNestedCheckboxIndexImport
      parentRoute: typeof rootRoute
    }
    '/components/signup-form/': {
      id: '/components/signup-form/'
      path: '/components/signup-form'
      fullPath: '/components/signup-form'
      preLoaderRoute: typeof ComponentsSignupFormIndexImport
      parentRoute: typeof rootRoute
    }
    '/concepts/debounce/': {
      id: '/concepts/debounce/'
      path: '/concepts/debounce'
      fullPath: '/concepts/debounce'
      preLoaderRoute: typeof ConceptsDebounceIndexImport
      parentRoute: typeof rootRoute
    }
    '/subscribe-pattern/event-emitter/': {
      id: '/subscribe-pattern/event-emitter/'
      path: '/subscribe-pattern/event-emitter'
      fullPath: '/subscribe-pattern/event-emitter'
      preLoaderRoute: typeof SubscribePatternEventEmitterIndexImport
      parentRoute: typeof rootRoute
    }
    '/subscribe-pattern/observer-pattern/': {
      id: '/subscribe-pattern/observer-pattern/'
      path: '/subscribe-pattern/observer-pattern'
      fullPath: '/subscribe-pattern/observer-pattern'
      preLoaderRoute: typeof SubscribePatternObserverPatternIndexImport
      parentRoute: typeof rootRoute
    }
    '/subscribe-pattern/rx-js/': {
      id: '/subscribe-pattern/rx-js/'
      path: '/subscribe-pattern/rx-js'
      fullPath: '/subscribe-pattern/rx-js'
      preLoaderRoute: typeof SubscribePatternRxJsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/subscribe-pattern': typeof SubscribePatternIndexRoute
  '/use-sync-external-store': typeof UseSyncExternalStoreIndexRoute
  '/components/contact-form': typeof ComponentsContactFormIndexRoute
  '/components/nested-checkbox': typeof ComponentsNestedCheckboxIndexRoute
  '/components/signup-form': typeof ComponentsSignupFormIndexRoute
  '/concepts/debounce': typeof ConceptsDebounceIndexRoute
  '/subscribe-pattern/event-emitter': typeof SubscribePatternEventEmitterIndexRoute
  '/subscribe-pattern/observer-pattern': typeof SubscribePatternObserverPatternIndexRoute
  '/subscribe-pattern/rx-js': typeof SubscribePatternRxJsIndexRoute
}

export interface FileRoutesByTo {
  '/subscribe-pattern': typeof SubscribePatternIndexRoute
  '/use-sync-external-store': typeof UseSyncExternalStoreIndexRoute
  '/components/contact-form': typeof ComponentsContactFormIndexRoute
  '/components/nested-checkbox': typeof ComponentsNestedCheckboxIndexRoute
  '/components/signup-form': typeof ComponentsSignupFormIndexRoute
  '/concepts/debounce': typeof ConceptsDebounceIndexRoute
  '/subscribe-pattern/event-emitter': typeof SubscribePatternEventEmitterIndexRoute
  '/subscribe-pattern/observer-pattern': typeof SubscribePatternObserverPatternIndexRoute
  '/subscribe-pattern/rx-js': typeof SubscribePatternRxJsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/subscribe-pattern/': typeof SubscribePatternIndexRoute
  '/use-sync-external-store/': typeof UseSyncExternalStoreIndexRoute
  '/components/contact-form/': typeof ComponentsContactFormIndexRoute
  '/components/nested-checkbox/': typeof ComponentsNestedCheckboxIndexRoute
  '/components/signup-form/': typeof ComponentsSignupFormIndexRoute
  '/concepts/debounce/': typeof ConceptsDebounceIndexRoute
  '/subscribe-pattern/event-emitter/': typeof SubscribePatternEventEmitterIndexRoute
  '/subscribe-pattern/observer-pattern/': typeof SubscribePatternObserverPatternIndexRoute
  '/subscribe-pattern/rx-js/': typeof SubscribePatternRxJsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/subscribe-pattern'
    | '/use-sync-external-store'
    | '/components/contact-form'
    | '/components/nested-checkbox'
    | '/components/signup-form'
    | '/concepts/debounce'
    | '/subscribe-pattern/event-emitter'
    | '/subscribe-pattern/observer-pattern'
    | '/subscribe-pattern/rx-js'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/subscribe-pattern'
    | '/use-sync-external-store'
    | '/components/contact-form'
    | '/components/nested-checkbox'
    | '/components/signup-form'
    | '/concepts/debounce'
    | '/subscribe-pattern/event-emitter'
    | '/subscribe-pattern/observer-pattern'
    | '/subscribe-pattern/rx-js'
  id:
    | '__root__'
    | '/subscribe-pattern/'
    | '/use-sync-external-store/'
    | '/components/contact-form/'
    | '/components/nested-checkbox/'
    | '/components/signup-form/'
    | '/concepts/debounce/'
    | '/subscribe-pattern/event-emitter/'
    | '/subscribe-pattern/observer-pattern/'
    | '/subscribe-pattern/rx-js/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  SubscribePatternIndexRoute: typeof SubscribePatternIndexRoute
  UseSyncExternalStoreIndexRoute: typeof UseSyncExternalStoreIndexRoute
  ComponentsContactFormIndexRoute: typeof ComponentsContactFormIndexRoute
  ComponentsNestedCheckboxIndexRoute: typeof ComponentsNestedCheckboxIndexRoute
  ComponentsSignupFormIndexRoute: typeof ComponentsSignupFormIndexRoute
  ConceptsDebounceIndexRoute: typeof ConceptsDebounceIndexRoute
  SubscribePatternEventEmitterIndexRoute: typeof SubscribePatternEventEmitterIndexRoute
  SubscribePatternObserverPatternIndexRoute: typeof SubscribePatternObserverPatternIndexRoute
  SubscribePatternRxJsIndexRoute: typeof SubscribePatternRxJsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  SubscribePatternIndexRoute: SubscribePatternIndexRoute,
  UseSyncExternalStoreIndexRoute: UseSyncExternalStoreIndexRoute,
  ComponentsContactFormIndexRoute: ComponentsContactFormIndexRoute,
  ComponentsNestedCheckboxIndexRoute: ComponentsNestedCheckboxIndexRoute,
  ComponentsSignupFormIndexRoute: ComponentsSignupFormIndexRoute,
  ConceptsDebounceIndexRoute: ConceptsDebounceIndexRoute,
  SubscribePatternEventEmitterIndexRoute:
    SubscribePatternEventEmitterIndexRoute,
  SubscribePatternObserverPatternIndexRoute:
    SubscribePatternObserverPatternIndexRoute,
  SubscribePatternRxJsIndexRoute: SubscribePatternRxJsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/subscribe-pattern/",
        "/use-sync-external-store/",
        "/components/contact-form/",
        "/components/nested-checkbox/",
        "/components/signup-form/",
        "/concepts/debounce/",
        "/subscribe-pattern/event-emitter/",
        "/subscribe-pattern/observer-pattern/",
        "/subscribe-pattern/rx-js/"
      ]
    },
    "/subscribe-pattern/": {
      "filePath": "subscribe-pattern/index.tsx"
    },
    "/use-sync-external-store/": {
      "filePath": "use-sync-external-store/index.tsx"
    },
    "/components/contact-form/": {
      "filePath": "components/contact-form/index.tsx"
    },
    "/components/nested-checkbox/": {
      "filePath": "components/nested-checkbox/index.tsx"
    },
    "/components/signup-form/": {
      "filePath": "components/signup-form/index.tsx"
    },
    "/concepts/debounce/": {
      "filePath": "concepts/debounce/index.tsx"
    },
    "/subscribe-pattern/event-emitter/": {
      "filePath": "subscribe-pattern/event-emitter/index.tsx"
    },
    "/subscribe-pattern/observer-pattern/": {
      "filePath": "subscribe-pattern/observer-pattern/index.tsx"
    },
    "/subscribe-pattern/rx-js/": {
      "filePath": "subscribe-pattern/rx-js/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
