/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UseSyncExternalStoreIndexImport } from './routes/use-sync-external-store/index'

// Create/Update Routes

const UseSyncExternalStoreIndexRoute = UseSyncExternalStoreIndexImport.update({
  id: '/use-sync-external-store/',
  path: '/use-sync-external-store/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/use-sync-external-store/': {
      id: '/use-sync-external-store/'
      path: '/use-sync-external-store'
      fullPath: '/use-sync-external-store'
      preLoaderRoute: typeof UseSyncExternalStoreIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/use-sync-external-store': typeof UseSyncExternalStoreIndexRoute
}

export interface FileRoutesByTo {
  '/use-sync-external-store': typeof UseSyncExternalStoreIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/use-sync-external-store/': typeof UseSyncExternalStoreIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/use-sync-external-store'
  fileRoutesByTo: FileRoutesByTo
  to: '/use-sync-external-store'
  id: '__root__' | '/use-sync-external-store/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  UseSyncExternalStoreIndexRoute: typeof UseSyncExternalStoreIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  UseSyncExternalStoreIndexRoute: UseSyncExternalStoreIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/use-sync-external-store/"
      ]
    },
    "/use-sync-external-store/": {
      "filePath": "use-sync-external-store/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
